# Generated by Django 2.1.7 on 2019-03-20 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20190320_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('weather_today', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
