# Generated by Django 2.1.7 on 2019-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20190320_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('total_km', models.IntegerField()),
                ('traveled_km', models.IntegerField()),
                ('total_fuel', models.IntegerField()),
                ('curent_consuption', models.IntegerField()),
            ],
        ),
    ]
