# Generated by Django 2.1.7 on 2020-03-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_homeweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeweather',
            name='room',
            field=models.TextField(default='', max_length='20'),
        ),
    ]
