# Generated by Django 2.1.7 on 2019-12-12 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_id', models.IntegerField()),
                ('node_id', models.TextField()),
                ('login', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='repos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('git_id', models.IntegerField()),
                ('node_id', models.TextField()),
                ('owner_id', models.IntegerField(default=None)),
                ('name', models.TextField()),
                ('full_name', models.TextField()),
                ('html', models.URLField()),
                ('description', models.TextField()),
                ('git_html', models.URLField()),
            ],
        ),
    ]
